language: node_js
node_js:
    - 0.6
    - 0.8
env:
    - JAVA_HOME=/usr/lib/jvm/java-1.6.0-openjdk
before_install:
    - ./travis/before.sh
install:
    - ./travis/install.sh
script:
    - ./travis/test.sh
notifications:
    email:
        - davglass@gmail.com
        - davglass@yahoo-inc.com
